---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: dev-myngxinkustomization
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./yaml/dev
  prune: true
  sourceRef:
    kind: GitRepository
    name: dev-mynginx
  targetNamespace: default
