---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: myngxinkustomization
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./yaml
  prune: true
  sourceRef:
    kind: GitRepository
    name: mynginx
  targetNamespace: default
